apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: flask-health-check-dev

namespace: development

resources:
- ../../base

patches:
- path: replica-patch.yaml
  target:
    kind: Deployment
    name: flask-health-check

images:
- name: ghcr.io/michigety/flask_gitops_argocd
  newTag: latest
