apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: flask-health-check

resources:
- deployment.yaml
- service.yaml
- ingress.yaml

images:
- name: ghcr.io/Michigety/flask_Gitops_argoCD
  newTag: ghcr.io/michigety/flask_gitops_argocd:main
- name: ghcr.io/your-username/flask-health-check
  newTag: latest
